<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

 use AppBundle\Entity\Produit;

class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    //Query Builder
    public function getAllCategories()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query
        -> select('p.categorie')
        -> distinct(true)
        -> from(produit::class, 'p')
        -> orderBy('p.categorie', 'ASC');
        //SELECT DISTINCT(categorie) FROProduit ORDER BY categorie ASC
        
        return $query->getQuery()->getResult();
        
    }
    
    //Create Query : 
    public function getAllCategories2()
    {
        $em = $this->getEntityManager();
        
        $query = $em->createQuery("SELECT DISTINCT(p.categorie) FROM AppBundle\Entity\Produit p ORDER BY p.categorie ASC");
        return $query->getResult();
    }
}
